### ISSUE TITLE
libxpm 3.5.12

### ISSUE THREAD

**Issue by Jan-E** [winlibs/libxpm#1]
@weltling 

There is a new version with a security fix:
http://seclists.org/oss-sec/2017/q1/167

Announce:
https://lists.freedesktop.org/archives/xorg/2016-December/058537.html

**Comment by weltling** [comment]
@Jan-E not even sure we're affected, but we can do that. There are yet some other updates, this particular one was uploaded as well. For 7.x all are added to the staging series.

Thanks.

**Comment by Jan-E** [comment]
Thanks. Will you update the sources in this repo later on?

**Comment by weltling** [comment]
Ohh, was updated, forgot to push. Just pushed all that :)

Thanks.

**Comment by Jan-E** [comment]
Thanks. Is the warning for a undefined snprintf in VC11 harmless or should there be an addition in src/Xpml.h? For instance:
```
#ifdef WIN32
#if _MSC_VER < 1900
#ifndef snprintf
#define snprintf _snprintf
#endif
#endif
#endif
```

**Comment by weltling** [comment]
You're right, lets fix it. It's harmless for PHP, but the repo is shared, anyway. Fixed the projects, the bins are under way.

Thanks.

**Comment by Jan-E** [comment]
OK, fine. Very off-topic here: could you take a look at
https://github.com/krakjoe/apcu/issues/223#issuecomment-288263701
https://github.com/krakjoe/apcu/pull/240#issuecomment-288365944

Weird crashes with php_apcu.dll x64 and an even more weird workaround (load a non-existent extension, which generates an error in php_errors.log).
